# 第三章 R 对象

## 3.1 原子型向量

In [1]:
die <- c(1,2,3,4,5,6)

die

[1] 1 2 3 4 5 6

In [2]:
is.vector(die)

[1] TRUE

In [3]:
five<-5 

five

[1] 5

In [4]:
length(five)

[1] 1

In [5]:
length(die)

[1] 6

In [7]:
int <- 1L
int

[1] 1

In [8]:
text<- c("ace","hearts")

text

[1] "ace"    "hearts"

### 3.1.1 双整型

In [9]:
die <- 1:6 

die

[1] 1 2 3 4 5 6

In [10]:
typeof(die)

[1] "integer"

In [11]:
# R 输入任何一个数值 都会默认 双整型

die<- c(1,2,3,4,5,6)

typeof(die)

Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

[1] "double"

### 3.1.2 整型

In [12]:
int <- c(-1L, 2L, 4L)

typeof(int)

[1] "integer"

In [13]:
sqrt(2)^2-2

[1] 4.440892e-16

### 3.1.3 字符型

In [14]:
text <- c("Hello","World")
text

[1] "Hello" "World"

In [15]:
typeof(text)

[1] "character"

### 3.1.4 逻辑型

In [17]:
3>4

[1] FALSE

In [18]:
logic<- c(TRUE, FALSE, TRUE)

logic 

[1]  TRUE FALSE  TRUE

In [19]:
typeof(logic)

[1] "logical"

In [20]:
typeof(F)

[1] "logical"

## 3.2 属性

In [21]:
attributes(die)

NULL

### 3.2.1 名称属性

In [22]:
names(die)

NULL

In [24]:
names(die)<-c("one","two","three","four","five","six")

die

one   two three  four  five   six 
    1     2     3     4     5     6

In [25]:
names(die)

[1] "one"   "two"   "three" "four"  "five"  "six"

In [26]:
die

one   two three  four  five   six 
    1     2     3     4     5     6

In [27]:
die+1

one   two three  four  five   six 
    2     3     4     5     6     7

In [28]:
# 一次性删除名称属性

names(die)<-NULL

die

Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

[1] 1 2 3 4 5 6

### 3.2.2 维度属性

In [29]:
dim(die)<- c(2,3)
die

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [31]:
dim(die)<-c(3,2)

die

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [33]:
dim(die)<-c(1,2,3)

die

, , 1

     [,1] [,2]
[1,]    1    2

, , 2

     [,1] [,2]
[1,]    3    4

, , 3

     [,1] [,2]
[1,]    5    6

In [34]:
dim(die)

[1] 1 2 3

## 3.3 矩阵

In [37]:
die<-1:6

die

[1] 1 2 3 4 5 6

In [38]:
m<- matrix(die, nrow=2)

m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [39]:
m<- matrix(die, nrow=2, byrow = TRUE)

m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## 3.4 数组

In [40]:
a<- array(c(11:14, 21:24, 31:34), dim=c(2,2,3))

a

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34

In [42]:
dim(a)

[1] 2 2 3

## 3.5 类 

In [43]:
dim(die)<-c(2,3)

In [44]:
die

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [45]:
typeof(die)

[1] "integer"

In [46]:
class(die)

[1] "matrix"

In [47]:
attributes(die)

$dim
[1] 2 3

In [48]:
class("Hello")

class(5)

[1] "character"

[1] "numeric"

### 3.5.2 因子

In [52]:
gender <- factor(c("male","female","female","male"))

typeof(gender)

attributes(gender)


[1] "integer"

$levels
[1] "female" "male"  

$class
[1] "factor"

In [53]:
unclass(gender)  # 查看 

[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"

In [54]:
gender

[1] male   female female male  
Levels: female male

In [56]:
class(gender)

[1] "factor"

In [55]:
# as.character 将一个因子 强制转换成 字符串 

as.character(gender)

Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

[1] "male"   "female" "female" "male"

In [57]:
gender

[1] male   female female male  
Levels: female male

In [59]:
class(gender)

attributes(gender)

[1] "factor"

$levels
[1] "female" "male"  

$class
[1] "factor"

## 3.6 强制转换

In [60]:
# 逻辑向量进行运算的时候， R会强制转换

sum(c(TRUE, TRUE, FALSE, FALSE))


Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

[1] 2

In [61]:
as.character(1)

[1] "1"

In [62]:
as.logical(1)

[1] TRUE

In [63]:
as.numeric(FALSE)

[1] 0

## 3.7 列表

In [64]:
list1 <- list(100:130, "R",list(TRUE, FALSE))

list1

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130

[[2]]
[1] "R"

[[3]]
[[3]][[1]]
[1] TRUE

[[3]][[2]]
[1] FALSE

In [66]:
card<- list("ace","hearts",1)

card

[[1]]
[1] "ace"

[[2]]
[1] "hearts"

[[3]]
[1] 1

## 3.8 数据框

In [67]:
df <- data.frame(face =c("ace","two","six"),
                suit= c("clubs","clubs","clubs"),
                value=c(1,2,3))

df

face suit  value
1 ace  clubs 1    
2 two  clubs 2    
3 six  clubs 3

In [68]:
# 名称

list(face="ace", suit ="hearts", value = 1)

c(face="ace", suit ="hearts", value = "one")

Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

$face
[1] "ace"

$suit
[1] "hearts"

$value
[1] 1

face     suit    value 
   "ace" "hearts"    "one"

[1] "list"

In [70]:
df

face suit  value
1 ace  clubs 1    
2 two  clubs 2    
3 six  clubs 3

In [71]:
typeof(df)

[1] "list"

In [72]:
class(df)

[1] "data.frame"

In [73]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ face : Factor w/ 3 levels "ace","six","two": 1 3 2
 $ suit : Factor w/ 1 level "clubs": 1 1 1
 $ value: num  1 2 3


In [77]:
# R 默认将字符存成 factor 防止 加入参数 
# stringsAsFactors = FALSE 


df <- data.frame(face =c("ace","two","six"),
                suit= c("clubs","clubs","clubs"),
                stringsAsFactors = FALSE)

df
str(df)

Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

face suit 
1 ace  clubs
2 two  clubs
3 six  clubs

'data.frame':	3 obs. of  2 variables:
 $ face: chr  "ace" "two" "six"
 $ suit: chr  "clubs" "clubs" "clubs"
